UI test is implemented
summermovedon/sdetTrainingUITask pull request #1
Opened 2022-02-17 18:16 UTC by summermovedon

2022-02-18 19:00 UTC, Leo1034 requested changes

2022-02-18 19:00 UTC, Leo1034 commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MainPage.java
> +    public static MainPage open() {
Предлагаю сделать базовый класс для тестов, в котором будет храниться драйвер, там же будет открываться стартовая страница. Все тестовые классы будут наследоваться от базового. И при создании объекта страницы, драйвер будет передаваться странице.

2022-02-18 19:00 UTC, Leo1034 commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MainPage.java
> +        findElement(uiMap.getProperty("startLoginButton")).click();
Поиск элементов нужно вынести из шага.

2022-02-18 19:00 UTC, Leo1034 commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +        findElement(uiMap.getProperty("composeButton")).click();
Тоже поиск элементов нужно вынести.

2022-02-18 19:20 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MainPage.java
> +    public static MainPage open() {
Правильно я понял: сделать класс BasePage и от него наследовать классы page object? Надо его сделать абстрактным?
И для чего надо открывать стартовую страницу не из класса MainPage?

2022-02-19 11:07 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MainPage.java
> +    public static MainPage open() {
сделано

2022-02-19 11:07 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MainPage.java
> +        findElement(uiMap.getProperty("startLoginButton")).click();
сделано

2022-02-19 11:07 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +        findElement(uiMap.getProperty("composeButton")).click();
сделано

2022-02-21 07:26 UTC, Leo1034 requested changes

2022-02-21 07:26 UTC, Leo1034 commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +    public static MailBoxPage create(WebDriver driver) {
Лучше сделать конструктор который будет принимать драйвер. Тогда момент создания страницы в тесте будет выглядеть как new MailBoxPage(driver)

2022-02-21 07:26 UTC, Leo1034 commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +    private WebElement getComposeButton() {
Поиск элементов лучше реализовать при помощи аннотации @FindBy

2022-02-21 10:38 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +    private WebElement getComposeButton() {
сделано

2022-02-21 10:38 UTC, summermovedon commented on src/test/java/com/gismatullin/sdettraininguitest/pages/MailBoxPage.java
> +    public static MailBoxPage create(WebDriver driver) {
сделано

2022-02-22 08:13 UTC, merged